name: "Connect to AWS EC2 instance"

on: workflow_dispatch

jobs:
  connect_ssh:
    name: Connect to EC2 instance via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Connect to AWS EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_DNS }}
          REMOTE_USER: ec2-user
          TARGET: /home/ec2-user

      - name: Install docker
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.AWS_DNS }}
          username: ec2-user
          port: 22 
          script: |
            sudo yum update -y &&\
             sudo amazon-linux-extras install docker &&\
              sudo yum install docker &&\
               sudo service docker start &&\ 
                 sudo usermod -a -G docker ec2-user &&\
                  newgrp docker
                  
      - name: Install docker-compose
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.AWS_DNS }}
          username: ec2-user
          port: 22 
          script: |
            sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose &&\
             sudo chmod +x /usr/local/bin/docker-compose
          
      - name: docker-compose build
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.AWS_DNS }}
          username: ec2-user
          port: 22 
          script: docker-compose build 
          
      - name: docker-compose up
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.AWS_DNS }}
          username: ec2-user
          port: 22 
          script: docker-compose up
